### ISSUE TITLE
Reference Error when starting this repo up

### ISSUE THREAD

**Issue by VietnamAirlines-lab** [McGRiMTV/GRiM#1]
**Describe the bug**
After forking this project and providing the correct credentials, I activated the script and received a 
```javascript
Reference Error: poop is not defined
``` 
I have no idea why this is and I assume your build is passing, so please help me out on this?

**To Reproduce**
1. Fork the repo
2. Put in correct credentials
3. Start the script

**Expected behavior**
The bot should start up and I should have all the features of the GRiM bot.

**Screenshots**
No fix your code boi.

**Additional context**
N/A

**Comment by VietnamAirlines-lab** [comment]
This is one massive bruh moment.

**Comment by VietnamAirlines-lab** [comment]
@McGRiMTV

**Comment by VietnamAirlines-lab** [comment]
@everyone @here

**Comment by McGRiMTV** [comment]
The bots full run code has not been posted on GitHub, this is something we hope to do in the future.

**Comment by VietnamAirlines-lab** [comment]
OK
